import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SupabaseProvider from "@/supabase/SupabaseProvider";
import { getSession } from "@/supabase/supabase-server";
import Image from "next/image";
import bgImage from "../../public/stradone.gif";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Laragh United GAA",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({ children }) {
  const session = await getSession();
  console.log("Start");
  console.log(session);
  console.log("End");
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider session={session}>
          <Navbar />
          <div className="relative min-h-screen">
            <div className="pb-2.5">{children}</div>
            <Footer />
          </div>
        </SupabaseProvider>
      </body>
    </html>
  );
}
