import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import SupabaseProvider from "@/supabase/SupabaseProvider";
import { getSession } from "@/supabase/supabase-server";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Laragh United GAA",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession();
  console.log("Start");
  console.log(session);
  console.log("End");
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider session={session}>
          <Navbar />

          {children}
        </SupabaseProvider>
      </body>
    </html>
  );
}
