import "./globals.css";
// import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SupabaseProvider from "@/supabase/SupabaseProvider";
import { getSession } from "@/supabase/supabase-server";
import StatusBar from "@/components/StatusBar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Laragh United GAA",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({ children }) {
  const session = await getSession();

  return (
    <html lang="en" className="font-sans">
      <body>
        <SupabaseProvider session={session}>
          <Navbar />
          {session ? <StatusBar id={session.user.id} /> : null}
          <div className="relative min-h-screen m-7">
            <div className="pb-56">{children}</div>
            <Footer />
          </div>
        </SupabaseProvider>
      </body>
    </html>
  );
}
